# Criar uma nova tarefa
POST http://localhost:3000/todos
Content-Type: application/json

{
  "title": "Nova tarefa",
  "completed": false
}

###

# Obter todas as tarefas
GET http://localhost:3000/todos

###

# Obter uma tarefa por ID
# Substitua :id pelo ID de uma tarefa específica
GET http://localhost:3000/todos/:id

###

# Atualizar uma tarefa
# Substitua :id pelo ID da tarefa que deseja atualizar
PUT http://localhost:3000/todos/:id
Content-Type: application/json

{
  "title": "Tarefa atualizada",
  "completed": true
}

###

# Deletar uma tarefa
# Substitua :id pelo ID da tarefa que deseja deletar
DELETE http://localhost:3000/todos/:id
